version: '3.8'

services:
  backend:
    image: ghcr.io/arturo-08/quick-backend-deploy:latest
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file: .env
    restart: on-failure:3
